const OK = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const DUPLICATE_KEY_ERROR = 11000;
const CONFLICT = 409;
const UNAUTHORIZED_ERROR = 401;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  OK,
  CREATED,
  DUPLICATE_KEY_ERROR,
  CONFLICT,
  UNAUTHORIZED_ERROR,
};
